-  name: Install Packages.
   package:
     name:
       - htop
       - vim
       - git
       - python3-psutil
       - snapd
       - compat-openssl10
       
-  name: Copy wallpaper file.
   copy:
     src: files/wallpaper.jpg
     dest: /home/mikael/Pictures/ansible-wallpaper.jpg
     owner: root
     group: root

-  name: Set Wallpaper.
   become_user: mikael
   dconf:
     key: "/org/gnome/desktop/background/picture-uri"
     value: "'file:////home/mikael/Pictures/ansible-wallpaper.jpg'"

-  name: Set Wallpaper position.
   become_user: mikael
   dconf:
     key: "/org/gnome/desktop/background/picture-options"
     value: "'zoom'"

-  name: Add microsoft VS Code repo. 
   yum_repository:
     name: vscode 
     description: VSCode YUM repo
     file: external_repos
     baseurl: https://packages.microsoft.com/yumrepos/vscode
     state: present
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     gpgcheck: yes 

-  name: Add Microsoft Teams repo.
   yum_repository:
     name: ms-teams 
     description: ms-teams YUM repo 
     file: external_repos
     baseurl: https://packages.microsoft.com/yumrepos/ms-teams
     state: present
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     gpgcheck: yes

-  name: Add microsoft Edge repo. 
   yum_repository:
     name: Edge
     description: edge YUM repo 
     baseurl: https://packages.microsoft.com/yumrepos/edge
     state: present
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     gpgcheck: yes

-  name: Add repository - Fedora
   yum_repository:
    name: microsoft
    description: Microsoft Repository
    baseurl: https://packages.microsoft.com/config/rhel/7/prod.repo
    state: present
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

-  name: Install Microsoft Applications.
   package:
     name:
       - teams
       - microsoft-edge-stable
       - code
       - powershell

- name: Install Slack with Snap.
  community.general.snap:
    name: slack
    classic: yes
    state: present

-  name: Install additional Applications with Snap.
   community.general.slack:
     name: bitwarden
     classic:
     state: present



