-  name: Install Packages.
   package:
     name:
       - htop
       - vim
       - git
       - python3-psutil
       - fedmod
       - flatpak-module-tools
              
-  name: Copy wallpaper file.
   copy:
     src: files/wallpaper.jpg
     dest: /home/mikael/Pictures/ansible-wallpaper.jpg
     owner: root
     group: root

-  name: Set Wallpaper.
   become_user: mikael
   dconf:
     key: "/org/gnome/desktop/background/picture-uri"
     value: "'file:////home/mikael/Pictures/ansible-wallpaper.jpg'"

-  name: Set Wallpaper position.
   become_user: mikael
   dconf:
     key: "/org/gnome/desktop/background/picture-options"
     value: "'zoom'"

-  name: Add microsoft VS Code repo. 
   yum_repository:
     name: vscode 
     description: VSCode YUM repo
     file: external_repos
     baseurl: https://packages.microsoft.com/yumrepos/vscode
     state: present
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     gpgcheck: yes 

-  name: Add Microsoft Teams repo.
   yum_repository:
     name: ms-teams 
     description: ms-teams YUM repo 
     file: external_repos
     baseurl: https://packages.microsoft.com/yumrepos/ms-teams
     state: present
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     gpgcheck: yes

-  name: Add microsoft Edge repo. 
   yum_repository:
     name: Edge
     description: edge YUM repo 
     baseurl: https://packages.microsoft.com/yumrepos/edge
     state: present
     gpgkey: https://packages.microsoft.com/keys/microsoft.asc
     gpgcheck: yes

-  name: Install Microsoft Applications.
   package:
     name:
       - teams
       - microsoft-edge-stable
       - code

-  name: Add Flatpak Repo
   ansible.builtin.command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install Slack with Flatpack.
  community.general.flatpak:
    name: com.slack.Slack
    state: present

